name = "dvode"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2016-2023 Jacob Williams"
license = "BSD-3"
description = "Modern Fortran Edition of the DVODE ODE Solver"
homepage = "https://github.com/jacobwilliams/dvode"

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = true