dvnlsd – dvode
dvnlsd Subroutine
269 statements
Source File
private subroutine dvnlsd(y, yh, ldyh, vsav, savf, ewt, acor, iwm, wm, f, jac, pdum, nflag, rpar, ipar)
subroutine dvnlsd is a nonlinear system solver, which uses functional iteration or a chord (modified newton) method. for the chord method direct linear algebraic system solvers are used. subroutine dvnlsd then handles the corrector phase of this integration package.
 call sequence input -- y, yh, ldyh, savf, ewt, acor, iwm, wm,
                        f, jac, nflag, rpar, ipar
 call sequence output -- yh, acor, wm, iwm, nflag
 common block variables accessed:
     /dvod01/ acnrm, crate, drc, h, rc, rl1, tq(5), tn, icf,
                jcur, meth, miter, n, nslp
     /dvod02/ hu, ncfn, netf, nfe, nje, nlu, nni, nqu, nst
 subroutines called by dvnlsd: f, daxpy, dcopy, dscal, dvjac, dvsol
 function routines called by dvnlsd: dvnorm
-----------------------------------------------------------------------
 communication with dvnlsd is done with the following variables. (for
 more details, please see the comments in the driver subroutine.)
 y          = the dependent variable, a vector of length n, input.
 yh         = the nordsieck (taylor) array, ldyh by lmax, input
              and output.  on input, it contains predicted values.
 ldyh       = a constant .ge. n, the first dimension of yh, input.
 vsav       = unused work array.
 savf       = a work array of length n.
 ewt        = an error weight vector of length n, input.
 acor       = a work array of length n, used for the accumulated
              corrections to the predicted y vector.
 wm,iwm     = real and integer work arrays associated with matrix
              operations in chord iteration (miter .ne. 0).
 f          = dummy name for user supplied routine for f.
 jac        = dummy name for user supplied jacobian routine.
 pdum       = unused dummy subroutine name.  included for uniformity
              over collection of integrators.
 nflag      = input/output flag, with values and meanings as follows:
              input
                  0 first call for this time step.
                 -1 convergence failure in previous call to dvnlsd.
                 -2 error test failure in dvstep.
              output
                  0 successful completion of nonlinear solver.
                 -1 convergence failure or singular matrix.
                 -2 unrecoverable error in matrix preprocessing
                    (cannot occur here).
                 -3 unrecoverable error in solution (cannot occur
                    here).
 rpar, ipar = dummy names for user's real and integer work arrays.
 ipup       = own variable flag with values and meanings as follows:
              0,            do not update the newton matrix.
              miter .ne. 0, update newton matrix, because it is the
                            initial step, order was changed, the error
                            test failed, or an update is indicated by
                            the scalar rc or step counter nst.
 for more details, see comments in driver subroutine.
dvjac is called by dvnlsd to compute and process the matrix p = i - hrl1j , where j is an approximation to the jacobian. here j is computed by the user-supplied routine jac if miter = 1 or 4, or by finite differencing if miter = 2, 3, or 5. if miter = 3, a diagonal approximation to j is used. if jsv = -1, j is computed from scratch in all cases. if jsv = 1 and miter = 1, 2, 4, or 5, and if the saved value of j is considered acceptable, then p is constructed from the saved j. j is stored in wm and replaced by p. if miter .ne. 3, p is then subjected to lu decomposition in preparation for later solution of linear systems with p as coefficient matrix. this is done by dgefa if miter = 1 or 2, and by dgbfa if miter = 4 or 5.
 call sequence input -- y, yh, ldyh, ewt, ftem, savf, wm, iwm,
                        f, jac, rpar, ipar
 call sequence output -- wm, iwm, ierpj
 common block variables accessed:
     /dvod01/  ccmxj, drc, h, rl1, tn, uround, icf, jcur, locjs,
               miter, msbj, n, nslj
     /dvod02/  nfe, nst, nje, nlu
 subroutines called by dvjac: f, jac, dacopy, dcopy, dgbfa, dgefa,
                              dscal
 function routines called by dvjac: dvnorm
-----------------------------------------------------------------------
 communication with dvjac is done with the following variables.  (for
 more details, please see the comments in the driver subroutine.)
 y          = vector containing predicted values on entry.
 yh         = the nordsieck array, an ldyh by lmax array, input.
 ldyh       = a constant .ge. n, the first dimension of yh, input.
 ewt        = an error weight vector of length n.
 savf       = array containing f evaluated at predicted y, input.
 wm         = real work space for matrices.  in the output, it contains
              the inverse diagonal matrix if miter = 3 and the lu
              decomposition of p if miter is 1, 2 , 4, or 5.
              storage of matrix elements starts at wm(3).
              storage of the saved jacobian starts at wm(locjs).
              wm also contains the following matrix-related data:
              wm(1) = sqrt(uround), used in numerical jacobian step.
              wm(2) = h*rl1, saved for later use if miter = 3.
 iwm        = integer work space containing pivot information,
              starting at iwm(31), if miter is 1, 2, 4, or 5.
              iwm also contains band parameters ml = iwm(1) and
              mu = iwm(2) if miter is 4 or 5.
 f          = dummy name for the user supplied subroutine for f.
 jac        = dummy name for the user supplied jacobian subroutine.
 rpar, ipar = dummy names for user's real and integer work arrays.
 rl1        = 1/el(2) (input).
 ierpj      = output error flag,  = 0 if no trouble, 1 if the p
              matrix is found to be singular.
 jcur       = output flag to indicate whether the jacobian matrix
              (or approximation) is now current.
              jcur = 0 means j is not current.
              jcur = 1 means j is current.
Arguments
Type Intent Optional Attributes Name
double precision :: y
double precision :: yh
integer :: ldyh
double precision :: vsav
double precision :: savf
double precision :: ewt
double precision :: acor
integer :: iwm
double precision :: wm
real :: f
integer :: jac
real :: pdum
integer :: nflag
double precision :: rpar
integer :: ipar
Calls
Contents
Common Blocks
dvod01 dvod02 dvod01 dvod02
Source Code
dvnlsd
Common Blocks
common /dvod01/
Type Attributes Name Initial
double precision :: acnrm
double precision :: ccmxj
double precision :: conp
double precision :: crate
double precision :: drc
real :: el(13)
double precision :: eta
double precision :: etamax
double precision :: h
double precision :: hmin
double precision :: hmxi
double precision :: hnew
double precision :: hscal
double precision :: prl1
double precision :: rc
double precision :: rl1
real :: tau(13)
real :: tq(5)
double precision :: tn
double precision :: uround
integer :: icf
integer :: init
integer :: ipup
integer :: jcur
integer :: jstart
integer :: jsv
integer :: kflag
integer :: kuth
integer :: l
integer :: lmax
integer :: lyh
integer :: lewt
integer :: lacor
integer :: lsavf
integer :: lwm
integer :: liwm
integer :: locjs
integer :: maxord
integer :: meth
integer :: miter
integer :: msbj
integer :: mxhnil
integer :: mxstep
integer :: n
integer :: newh
integer :: newq
integer :: nhnil
integer :: nq
integer :: nqnyh
integer :: nqwait
integer :: nslj
integer :: nslp
integer :: nyh
common /dvod02/
Type Attributes Name Initial
double precision :: hu
integer :: ncfn
integer :: netf
integer :: nfe
integer :: nje
integer :: nlu
integer :: nni
integer :: nqu
integer :: nst
common /dvod01/
Type Attributes Name Initial
double precision :: acnrm
double precision :: ccmxj
double precision :: conp
double precision :: crate
double precision :: drc
real :: el(13)
double precision :: eta
double precision :: etamax
double precision :: h
double precision :: hmin
double precision :: hmxi
double precision :: hnew
double precision :: hscal
double precision :: prl1
double precision :: rc
double precision :: rl1
real :: tau(13)
real :: tq(5)
double precision :: tn
double precision :: uround
integer :: icf
integer :: init
integer :: ipup
integer :: jcur
integer :: jstart
integer :: jsv
integer :: kflag
integer :: kuth
integer :: l
integer :: lmax
integer :: lyh
integer :: lewt
integer :: lacor
integer :: lsavf
integer :: lwm
integer :: liwm
integer :: locjs
integer :: maxord
integer :: meth
integer :: miter
integer :: msbj
integer :: mxhnil
integer :: mxstep
integer :: n
integer :: newh
integer :: newq
integer :: nhnil
integer :: nq
integer :: nqnyh
integer :: nqwait
integer :: nslj
integer :: nslp
integer :: nyh
common /dvod02/
Type Attributes Name Initial
double precision :: hu
integer :: ncfn
integer :: netf
integer :: nfe
integer :: nje
integer :: nlu
integer :: nni
integer :: nqu
integer :: nst
Source Code
      subroutine dvnlsd(y,yh,ldyh,vsav,savf,ewt,acor,iwm,wm,f,jac,pdum, &
                        nflag,rpar,ipar)
      implicit none
      external f , jac , pdum
      double precision y , yh , vsav , savf , ewt , acor , wm , rpar
      integer ldyh , iwm , nflag , ipar
      dimension y(*) , yh(ldyh,*) , vsav(*) , savf(*) , ewt(*) , acor(*)&
                , iwm(*) , wm(*) , rpar(*) , ipar(*)
! type declarations for labeled common block dvod01 --------------------
!
      double precision acnrm , ccmxj , conp , crate , drc , el , eta ,  &
                       etamax , h , hmin , hmxi , hnew , hscal , prl1 , &
                       rc , rl1 , tau , tq , tn , uround
      integer icf , init , ipup , jcur , jstart , jsv , kflag , kuth ,  &
              l , lmax , lyh , lewt , lacor , lsavf , lwm , liwm ,      &
              locjs , maxord , meth , miter , msbj , mxhnil , mxstep ,  &
              n , newh , newq , nhnil , nq , nqnyh , nqwait , nslj ,    &
              nslp , nyh
!
! type declarations for labeled common block dvod02 --------------------
!
      double precision hu
      integer ncfn , netf , nfe , nje , nlu , nni , nqu , nst
!
! type declarations for local variables --------------------------------
!
      double precision ccmax , crdown , cscale , dcon , del , delp ,    &
                       one , rdiv , two , zero
      integer i , ierpj , iersl , m , maxcor , msbp
!
! type declaration for function subroutines called ---------------------
!
!      double precision dvnorm
!-----------------------------------------------------------------------
! the following fortran-77 declaration is to cause the values of the
! listed (local) variables to be saved between calls to this integrator.
!-----------------------------------------------------------------------
      save ccmax , crdown , maxcor , msbp , rdiv , one , two , zero
!
      common /dvod01/ acnrm , ccmxj , conp , crate , drc , el(13) ,     &
                      eta , etamax , h , hmin , hmxi , hnew , hscal ,   &
                      prl1 , rc , rl1 , tau(13) , tq(5) , tn , uround , &
                      icf , init , ipup , jcur , jstart , jsv , kflag , &
                      kuth , l , lmax , lyh , lewt , lacor , lsavf ,    &
                      lwm , liwm , locjs , maxord , meth , miter ,      &
                      msbj , mxhnil , mxstep , n , newh , newq , nhnil ,&
                      nq , nqnyh , nqwait , nslj , nslp , nyh
      common /dvod02/ hu , ncfn , netf , nfe , nje , nlu , nni , nqu ,  &
                      nst
!
      data ccmax/0.3d0/ , crdown/0.3d0/ , maxcor/3/ , msbp/20/ ,        &
           rdiv/2.0d0/
      data one/1.0d0/ , two/2.0d0/ , zero/0.0d0/
!-----------------------------------------------------------------------
! on the first step, on a change of method order, or after a
! nonlinear convergence failure with nflag = -2, set ipup = miter
! to force a jacobian update when miter .ne. 0.
!-----------------------------------------------------------------------
      if ( jstart==0 ) nslp = 0
      if ( nflag==0 ) icf = 0
      if ( nflag==-2 ) ipup = miter
      if ( (jstart==0) .or. (jstart==-1) ) ipup = miter
! if this is functional iteration, set crate .eq. 1 and drop to 220
      if ( miter==0 ) then
         crate = one
         goto 100
      endif
!-----------------------------------------------------------------------
! rc is the ratio of new to old values of the coefficient h/el(2)=h/l1.
! when rc differs from 1 by more than ccmax, ipup is set to miter
! to force dvjac to be called, if a jacobian is involved.
! in any case, dvjac is called at least every msbp steps.
!-----------------------------------------------------------------------
      drc = abs(rc-one)
      if ( drc>ccmax .or. nst>=nslp+msbp ) ipup = miter
!-----------------------------------------------------------------------
! up to maxcor corrector iterations are taken.  a convergence test is
! made on the r.m.s. norm of each correction, weighted by the error
! weight vector ewt.  the sum of the corrections is accumulated in the
! vector acor(i).  the yh array is not altered in the corrector loop.
!-----------------------------------------------------------------------
 100  m = 0
      delp = zero
      call dcopy(n,yh(1,1),1,y,1)
      call f(n,tn,y,savf,rpar,ipar)
      nfe = nfe + 1
      if ( ipup>0 ) then
!-----------------------------------------------------------------------
! if indicated, the matrix p = i - h*rl1*j is reevaluated and
! preprocessed before starting the corrector iteration.  ipup is set
! to 0 as an indicator that this has been done.
!-----------------------------------------------------------------------
         call dvjac(y,yh,ldyh,ewt,acor,savf,wm,iwm,f,jac,ierpj,rpar,    &
                    ipar)
         ipup = 0
         rc = one
         drc = zero
         crate = one
         nslp = nst
! if matrix is singular, take error return to force cut in step size. --
         if ( ierpj/=0 ) goto 400
      endif
      do i = 1 , n
         acor(i) = zero
      enddo
! this is a looping point for the corrector iteration. -----------------
 200  if ( miter/=0 ) then
!-----------------------------------------------------------------------
! in the case of the chord method, compute the corrector error,
! and solve the linear system with that as right-hand side and
! p as coefficient matrix.  the correction is scaled by the factor
! 2/(1+rc) to account for changes in h*rl1 since the last dvjac call.
!-----------------------------------------------------------------------
         do i = 1 , n
            y(i) = (rl1*h)*savf(i) - (rl1*yh(i,2)+acor(i))
         enddo
         call dvsol(wm,iwm,y,iersl)
         nni = nni + 1
         if ( iersl>0 ) goto 300
         if ( meth==2 .and. rc/=one ) then
            cscale = two/(one+rc)
            call dscal(n,cscale,y,1)
         endif
         del = dvnorm(n,y,ewt)
         call daxpy(n,one,y,1,acor,1)
         do i = 1 , n
            y(i) = yh(i,1) + acor(i)
         enddo
      else
!-----------------------------------------------------------------------
! in the case of functional iteration, update y directly from
! the result of the last function evaluation.
!-----------------------------------------------------------------------
         do i = 1 , n
            savf(i) = rl1*(h*savf(i)-yh(i,2))
         enddo
         do i = 1 , n
            y(i) = savf(i) - acor(i)
         enddo
         del = dvnorm(n,y,ewt)
         do i = 1 , n
            y(i) = yh(i,1) + savf(i)
         enddo
         call dcopy(n,savf,1,acor,1)
      endif
!-----------------------------------------------------------------------
! test for convergence.  if m .gt. 0, an estimate of the convergence
! rate constant is stored in crate, and this is used in the test.
!-----------------------------------------------------------------------
      if ( m/=0 ) crate = max(crdown*crate,del/delp)
      dcon = del*min(one,crate)/tq(4)
      if ( dcon<=one ) then
!
! return for successful step. ------------------------------------------
         nflag = 0
         jcur = 0
         icf = 0
         if ( m==0 ) acnrm = del
         if ( m>0 ) acnrm = dvnorm(n,acor,ewt)
         goto 99999
      else
         m = m + 1
         if ( m/=maxcor ) then
            if ( m<2 .or. del<=rdiv*delp ) then
               delp = del
               call f(n,tn,y,savf,rpar,ipar)
               nfe = nfe + 1
               goto 200
            endif
         endif
      endif
!
 300  if ( miter/=0 .and. jcur/=1 ) then
         icf = 1
         ipup = miter
         goto 100
      endif
!
 400  nflag = -1
      icf = 2
      ipup = miter
      return
99999 end subroutine dvnlsd
Call graph
dvnlsd calls dscal, dgefa, dgbfa, dvjac, dacopy, dcopy, dvnorm, dvsol, daxpy
dgefa calls dscal, daxpy, idamax
dgbfa calls dscal, daxpy, idamax
dacopy calls dcopy
dvsol calls dgbsl, dgesl
dgbsl calls daxpy, ddot
dgesl calls daxpy, ddot