dvsol – dvode
dvsol Subroutine
124 statements
Source File
private subroutine dvsol(wm, iwm, x, iersl)
Arguments
Type Intent Optional Attributes Name
double precision :: wm
integer :: iwm
double precision :: x
integer :: iersl
Calls
Called by
Contents
Common Blocks
dvod01 dvod01 dvod02
Source Code
dvsol
Common Blocks
common /dvod01/
Type Attributes Name Initial
double precision :: acnrm
double precision :: ccmxj
double precision :: conp
double precision :: crate
double precision :: drc
real :: el(13)
double precision :: eta
double precision :: etamax
double precision :: h
double precision :: hmin
double precision :: hmxi
double precision :: hnew
double precision :: hscal
double precision :: prl1
double precision :: rc
double precision :: rl1
real :: tau(13)
real :: tq(5)
double precision :: tn
double precision :: uround
integer :: icf
integer :: init
integer :: ipup
integer :: jcur
integer :: jstart
integer :: jsv
integer :: kflag
integer :: kuth
integer :: l
integer :: lmax
integer :: lyh
integer :: lewt
integer :: lacor
integer :: lsavf
integer :: lwm
integer :: liwm
integer :: locjs
integer :: maxord
integer :: meth
integer :: miter
integer :: msbj
integer :: mxhnil
integer :: mxstep
integer :: n
integer :: newh
integer :: newq
integer :: nhnil
integer :: nq
integer :: nqnyh
integer :: nqwait
integer :: nslj
integer :: nslp
integer :: nyh
common /dvod01/
Type Attributes Name Initial
real :: rvod1(48)
integer :: ivod1(33)
common /dvod02/
Type Attributes Name Initial
real :: rvod2(1)
integer :: ivod2(8)
Source Code
      subroutine dvsol(wm,iwm,x,iersl)
      implicit none
      double precision wm , x
      integer iwm , iersl
      dimension wm(*) , iwm(*) , x(*)
!-----------------------------------------------------------------------
! call sequence input -- wm, iwm, x
! call sequence output -- x, iersl
! common block variables accessed:
!     /dvod01/ -- h, rl1, miter, n
!
! subroutines called by dvsol: dgesl, dgbsl
! function routines called by dvsol: none
!-----------------------------------------------------------------------
! this routine manages the solution of the linear system arising from
! a chord iteration.  it is called if miter .ne. 0.
! if miter is 1 or 2, it calls dgesl to accomplish this.
! if miter = 3 it updates the coefficient h*rl1 in the diagonal
! matrix, and then computes the solution.
! if miter is 4 or 5, it calls dgbsl.
! communication with dvsol uses the following variables:
! wm    = real work space containing the inverse diagonal matrix if
!         miter = 3 and the lu decomposition of the matrix otherwise.
!         storage of matrix elements starts at wm(3).
!         wm also contains the following matrix-related data:
!         wm(1) = sqrt(uround) (not used here),
!         wm(2) = hrl1, the previous value of h*rl1, used if miter = 3.
! iwm   = integer work space containing pivot information, starting at
!         iwm(31), if miter is 1, 2, 4, or 5.  iwm also contains band
!         parameters ml = iwm(1) and mu = iwm(2) if miter is 4 or 5.
! x     = the right-hand side vector on input, and the solution vector
!         on output, of length n.
! iersl = output flag.  iersl = 0 if no trouble occurred.
!         iersl = 1 if a singular matrix arose with miter = 3.
!-----------------------------------------------------------------------
!
! type declarations for labeled common block dvod01 --------------------
!
      double precision acnrm , ccmxj , conp , crate , drc , el , eta ,  &
                       etamax , h , hmin , hmxi , hnew , hscal , prl1 , &
                       rc , rl1 , tau , tq , tn , uround
      integer icf , init , ipup , jcur , jstart , jsv , kflag , kuth ,  &
              l , lmax , lyh , lewt , lacor , lsavf , lwm , liwm ,      &
              locjs , maxord , meth , miter , msbj , mxhnil , mxstep ,  &
              n , newh , newq , nhnil , nq , nqnyh , nqwait , nslj ,    &
              nslp , nyh
!
! type declarations for local variables --------------------------------
!
      integer i , meband , ml , mu
      double precision di , hrl1 , one , phrl1 , r , zero
!-----------------------------------------------------------------------
! the following fortran-77 declaration is to cause the values of the
! listed (local) variables to be saved between calls to this integrator.
!-----------------------------------------------------------------------
      save one , zero
!
      common /dvod01/ acnrm , ccmxj , conp , crate , drc , el(13) ,     &
                      eta , etamax , h , hmin , hmxi , hnew , hscal ,   &
                      prl1 , rc , rl1 , tau(13) , tq(5) , tn , uround , &
                      icf , init , ipup , jcur , jstart , jsv , kflag , &
                      kuth , l , lmax , lyh , lewt , lacor , lsavf ,    &
                      lwm , liwm , locjs , maxord , meth , miter ,      &
                      msbj , mxhnil , mxstep , n , newh , newq , nhnil ,&
                      nq , nqnyh , nqwait , nslj , nslp , nyh
!
      data one/1.0d0/ , zero/0.0d0/
!
      iersl = 0
      select case (miter)
      case (3)
!
         phrl1 = wm(2)
         hrl1 = h*rl1
         wm(2) = hrl1
         if ( hrl1/=phrl1 ) then
            r = hrl1/phrl1
            do i = 1 , n
               di = one - r*(one-one/wm(i+2))
               if ( abs(di)==zero ) goto 100
               wm(i+2) = one/di
            enddo
         endif
!
         do i = 1 , n
            x(i) = wm(i+2)*x(i)
         enddo
         return
      case (4,5)
!
         ml = iwm(1)
         mu = iwm(2)
         meband = 2*ml + mu + 1
         call dgbsl(wm(3),meband,n,ml,mu,iwm(31),x,0)
         goto 99999
      case default
         call dgesl(wm(3),n,n,iwm(31),x,0)
         return
      end select
 100  iersl = 1
      return
99999 end subroutine dvsol
Call graph
dvsol calls dgbsl, dgesl
dgbsl calls ddot, daxpy
dgesl calls ddot, daxpy
dvnlsd calls dvsol